//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Front_End.ServiceReferenceBoleta {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceBoleta.wsBoletaSoap")]
    public interface wsBoletaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarBoletaCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListarBoletaCliente(string CodCLiente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarBoletaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarBoletaClienteAsync(string CodCLiente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarBoletaAnuladaCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListarBoletaAnuladaCliente(string CodCLiente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarBoletaAnuladaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarBoletaAnuladaClienteAsync(string CodCLiente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Agregar(string codCliente, string codVendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> AgregarAsync(string codCliente, string codVendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarVentaFecha", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConsultarVentaFecha(string usuario, string semana);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarVentaFecha", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ConsultarVentaFechaAsync(string usuario, string semana);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsBoletaSoapChannel : Front_End.ServiceReferenceBoleta.wsBoletaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsBoletaSoapClient : System.ServiceModel.ClientBase<Front_End.ServiceReferenceBoleta.wsBoletaSoap>, Front_End.ServiceReferenceBoleta.wsBoletaSoap {
        
        public wsBoletaSoapClient() {
        }
        
        public wsBoletaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsBoletaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsBoletaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsBoletaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ListarBoletaCliente(string CodCLiente) {
            return base.Channel.ListarBoletaCliente(CodCLiente);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarBoletaClienteAsync(string CodCLiente) {
            return base.Channel.ListarBoletaClienteAsync(CodCLiente);
        }
        
        public System.Data.DataSet ListarBoletaAnuladaCliente(string CodCLiente) {
            return base.Channel.ListarBoletaAnuladaCliente(CodCLiente);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarBoletaAnuladaClienteAsync(string CodCLiente) {
            return base.Channel.ListarBoletaAnuladaClienteAsync(CodCLiente);
        }
        
        public string[] Agregar(string codCliente, string codVendedor) {
            return base.Channel.Agregar(codCliente, codVendedor);
        }
        
        public System.Threading.Tasks.Task<string[]> AgregarAsync(string codCliente, string codVendedor) {
            return base.Channel.AgregarAsync(codCliente, codVendedor);
        }
        
        public System.Data.DataSet ConsultarVentaFecha(string usuario, string semana) {
            return base.Channel.ConsultarVentaFecha(usuario, semana);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ConsultarVentaFechaAsync(string usuario, string semana) {
            return base.Channel.ConsultarVentaFechaAsync(usuario, semana);
        }
    }
}
