//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Front_End.ServiceReferenceProducto {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceProducto.wsProductoSoap")]
    public interface wsProductoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarProdCat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListarProdCat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarProdCat", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarProdCatAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Agregar(string nombre, string unidad_de_medida, float precio, int stock, string CodCatetegoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AgregarAsync(string nombre, string unidad_de_medida, float precio, int stock, string CodCatetegoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Eliminar(string CodProducto, string Codcategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminarAsync(string CodProducto, string Codcategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modificar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Modificar(string codProducto, string nombre, string unidad_de_medida, float precio, int stock, string CodCatetegoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modificar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ModificarAsync(string codProducto, string nombre, string unidad_de_medida, float precio, int stock, string CodCatetegoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buscar(string texto, string criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsProductoSoapChannel : Front_End.ServiceReferenceProducto.wsProductoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsProductoSoapClient : System.ServiceModel.ClientBase<Front_End.ServiceReferenceProducto.wsProductoSoap>, Front_End.ServiceReferenceProducto.wsProductoSoap {
        
        public wsProductoSoapClient() {
        }
        
        public wsProductoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsProductoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsProductoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsProductoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public System.Data.DataSet ListarProdCat() {
            return base.Channel.ListarProdCat();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarProdCatAsync() {
            return base.Channel.ListarProdCatAsync();
        }
        
        public bool Agregar(string nombre, string unidad_de_medida, float precio, int stock, string CodCatetegoria) {
            return base.Channel.Agregar(nombre, unidad_de_medida, precio, stock, CodCatetegoria);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarAsync(string nombre, string unidad_de_medida, float precio, int stock, string CodCatetegoria) {
            return base.Channel.AgregarAsync(nombre, unidad_de_medida, precio, stock, CodCatetegoria);
        }
        
        public bool Eliminar(string CodProducto, string Codcategoria) {
            return base.Channel.Eliminar(CodProducto, Codcategoria);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarAsync(string CodProducto, string Codcategoria) {
            return base.Channel.EliminarAsync(CodProducto, Codcategoria);
        }
        
        public bool Modificar(string codProducto, string nombre, string unidad_de_medida, float precio, int stock, string CodCatetegoria) {
            return base.Channel.Modificar(codProducto, nombre, unidad_de_medida, precio, stock, CodCatetegoria);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarAsync(string codProducto, string nombre, string unidad_de_medida, float precio, int stock, string CodCatetegoria) {
            return base.Channel.ModificarAsync(codProducto, nombre, unidad_de_medida, precio, stock, CodCatetegoria);
        }
        
        public System.Data.DataSet Buscar(string texto, string criterio) {
            return base.Channel.Buscar(texto, criterio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio) {
            return base.Channel.BuscarAsync(texto, criterio);
        }
    }
}
