//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Front_End.ServiceReferenceVendedor {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceVendedor.wsVendedorSoap")]
    public interface wsVendedorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Login(string CodVendedor, string Contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> LoginAsync(string CodVendedor, string Contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Agregar(string Apellidos, string Nombres, string Usuario, string Contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AgregarAsync(string Apellidos, string Nombres, string Usuario, string Contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modificar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Modificar(string CodVendedor, string Apellidos, string Nombres, string Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modificar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ModificarAsync(string CodVendedor, string Apellidos, string Nombres, string Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Eliminar(string CodVendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminarAsync(string CodVendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buscar(string texto, string criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsVendedorSoapChannel : Front_End.ServiceReferenceVendedor.wsVendedorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsVendedorSoapClient : System.ServiceModel.ClientBase<Front_End.ServiceReferenceVendedor.wsVendedorSoap>, Front_End.ServiceReferenceVendedor.wsVendedorSoap {
        
        public wsVendedorSoapClient() {
        }
        
        public wsVendedorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsVendedorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsVendedorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsVendedorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] Login(string CodVendedor, string Contrasena) {
            return base.Channel.Login(CodVendedor, Contrasena);
        }
        
        public System.Threading.Tasks.Task<string[]> LoginAsync(string CodVendedor, string Contrasena) {
            return base.Channel.LoginAsync(CodVendedor, Contrasena);
        }
        
        public System.Data.DataSet Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public bool Agregar(string Apellidos, string Nombres, string Usuario, string Contrasena) {
            return base.Channel.Agregar(Apellidos, Nombres, Usuario, Contrasena);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarAsync(string Apellidos, string Nombres, string Usuario, string Contrasena) {
            return base.Channel.AgregarAsync(Apellidos, Nombres, Usuario, Contrasena);
        }
        
        public bool Modificar(string CodVendedor, string Apellidos, string Nombres, string Usuario) {
            return base.Channel.Modificar(CodVendedor, Apellidos, Nombres, Usuario);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarAsync(string CodVendedor, string Apellidos, string Nombres, string Usuario) {
            return base.Channel.ModificarAsync(CodVendedor, Apellidos, Nombres, Usuario);
        }
        
        public bool Eliminar(string CodVendedor) {
            return base.Channel.Eliminar(CodVendedor);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarAsync(string CodVendedor) {
            return base.Channel.EliminarAsync(CodVendedor);
        }
        
        public System.Data.DataSet Buscar(string texto, string criterio) {
            return base.Channel.Buscar(texto, criterio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio) {
            return base.Channel.BuscarAsync(texto, criterio);
        }
    }
}
